package application_appareils;

import GestionSocket.GestionSocket;
import RequestResponseDISMAP.IDISMAP;

import RequestResponseDISMAP.RequestDISMAP;
import RequestResponseDISMAP.ResponseDISMAP;
import java.awt.BorderLayout;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.Security;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SecretKey;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.bouncycastle.jce.provider.BouncyCastleProvider;


/**
 *
 * @author bobmastrolilli
 */
public class ClientGUI extends javax.swing.JFrame implements IDISMAP {

    private boolean connect = false;
    private GestionSocket GSocket = null;
    private int numeroSerieCourant;
    Vector VentesRealiseeSession ;
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        VentesRealiseeSession=new Vector();
        this.Adresse_TP.setEnabled(false);
        this.GSocket = new GestionSocket();
        LOGIN_OK.setEnabled(false);
        SEARCH_GOODS_OK.setEnabled(false);
        TAKE_GOODS_OK.setEnabled(false);
        BUY_GOODS_OK.setEnabled(false);
        DELIVERY_GOODS_OK.setEnabled(false);
        LIST_SALES_OK.setEnabled(false);
        CREATE_USER_BUTTON.setEnabled(false);
        System.out.println("NAME = " + TABS.getComponentAt(0).getName());
        Adresse_TP.setText("Retiré dans le mummystore");
    }

    public GestionSocket getGSocket() {
        return GSocket;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TABS = new javax.swing.JTabbedPane();
        TabConnexion = new javax.swing.JPanel();
        LB_machine = new javax.swing.JLabel();
        Serveur_TextField = new javax.swing.JTextField();
        LB_port = new javax.swing.JLabel();
        Port_TextField = new javax.swing.JTextField();
        Connect_Bouton = new javax.swing.JButton();
        Deconnect_Bouton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_user = new javax.swing.JTextField();
        TF_password = new javax.swing.JTextField();
        LOGIN_OK = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        CREATE_USER_BUTTON = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Appareils_jTABLE = new javax.swing.JTable();
        SEARCH_GOODS_OK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TypePrecis_CB = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        TAKE_GOODS_OK = new javax.swing.JButton();
        NumSerie_TF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        BUY_GOODS_OK = new javax.swing.JButton();
        modePaiement_CB = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        DELIVERYGOOD_CB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Adresse_TP = new javax.swing.JTextArea();
        DELIVERY_GOODS_OK = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Nom_TF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Appareils_jTABLE1 = new javax.swing.JTable();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        LIST_SALES_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client CheckIn");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TABS.setToolTipText("");

        LB_machine.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LB_machine.setText("Serveur : ");

        Serveur_TextField.setText("127.0.0.1");

        LB_port.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LB_port.setText("Port : ");

        Port_TextField.setText("2000");

        Connect_Bouton.setText("Connect");
        Connect_Bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Connect_BoutonActionPerformed(evt);
            }
        });

        Deconnect_Bouton.setText("Disconnect");
        Deconnect_Bouton.setEnabled(false);
        Deconnect_Bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deconnect_BoutonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Connexion au serveur.");

        javax.swing.GroupLayout TabConnexionLayout = new javax.swing.GroupLayout(TabConnexion);
        TabConnexion.setLayout(TabConnexionLayout);
        TabConnexionLayout.setHorizontalGroup(
            TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(TabConnexionLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel15)
                        .addGap(0, 620, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabConnexionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Connect_Bouton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Deconnect_Bouton)))
                .addContainerGap())
            .addGroup(TabConnexionLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_machine)
                    .addComponent(LB_port))
                .addGap(18, 18, 18)
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Port_TextField)
                    .addComponent(Serveur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabConnexionLayout.setVerticalGroup(
            TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_machine)
                    .addComponent(Serveur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Port_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_port))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(TabConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deconnect_Bouton)
                    .addComponent(Connect_Bouton))
                .addContainerGap())
        );

        TABS.addTab("Connexion", TabConnexion);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nom");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mot de passe");

        TF_user.setText("Bob");

        TF_password.setText("Bob");
        TF_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_passwordActionPerformed(evt);
            }
        });

        LOGIN_OK.setText("OK");
        LOGIN_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_OKActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Connexion au serveur.");

        CREATE_USER_BUTTON.setText("CreateUser");
        CREATE_USER_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATE_USER_BUTTONActionPerformed(evt);
            }
        });

        jLabel3.setText("Pas encore d'identifiants ? ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel16)
                        .addGap(256, 256, 256)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_password)
                    .addComponent(TF_user, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CREATE_USER_BUTTON)
                    .addComponent(LOGIN_OK)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TF_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CREATE_USER_BUTTON))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(TF_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(LOGIN_OK)
                .addGap(19, 19, 19))
        );

        TABS.addTab("Login", jPanel1);

        jPanel2.setEnabled(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Recherche Appareil Précis");

        Appareils_jTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NumSérie", "TypeGeneral", "TypePrécis", "Marque", "PrixVente effectif", "EtatSituation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Appareils_jTABLE);
        if (Appareils_jTABLE.getColumnModel().getColumnCount() > 0) {
            Appareils_jTABLE.getColumnModel().getColumn(0).setHeaderValue("IdFacture");
            Appareils_jTABLE.getColumnModel().getColumn(1).setHeaderValue("TypeGeneral");
            Appareils_jTABLE.getColumnModel().getColumn(5).setResizable(false);
        }

        SEARCH_GOODS_OK.setText("OK");
        SEARCH_GOODS_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_GOODS_OKActionPerformed(evt);
            }
        });

        jLabel5.setText("Type Précis : ");

        TypePrecis_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APE_BLANC", "APE_NOIR", "AGE_BLANC", "AGE_NOIR", "AAV_BLANC", "AAV_NOIR", "OTHER_BLANC", "OTHER_NOIR" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TypePrecis_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SEARCH_GOODS_OK)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TypePrecis_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SEARCH_GOODS_OK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TABS.addTab("SEARCH-GOOD", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Achat de l'article PHASE 1 ");

        jLabel2.setText("Numéro de Série");

        TAKE_GOODS_OK.setText("OK");
        TAKE_GOODS_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAKE_GOODS_OKActionPerformed(evt);
            }
        });

        NumSerie_TF.setText("1");
        NumSerie_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumSerie_TFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 810, Short.MAX_VALUE)
                        .addComponent(TAKE_GOODS_OK))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(86, 86, 86)
                        .addComponent(NumSerie_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NumSerie_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(TAKE_GOODS_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TABS.addTab("TAKE_GOODS", jPanel3);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Achat de l'article : Phase 2");

        jLabel13.setText("Mode de paiement : ");

        BUY_GOODS_OK.setText("OK");
        BUY_GOODS_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUY_GOODS_OKActionPerformed(evt);
            }
        });

        modePaiement_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CASH", "CARTE", "NATURE" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(38, 38, 38)
                        .addComponent(modePaiement_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUY_GOODS_OK)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(modePaiement_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(BUY_GOODS_OK)
                .addContainerGap())
        );

        TABS.addTab("BUY_GOODS", jPanel4);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Delivery : Choix d'un mode ");

        DELIVERYGOOD_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Embarquement imédiat", "Demande de livraison" }));
        DELIVERYGOOD_CB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DELIVERYGOOD_CBMousePressed(evt);
            }
        });
        DELIVERYGOOD_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELIVERYGOOD_CBActionPerformed(evt);
            }
        });
        DELIVERYGOOD_CB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DELIVERYGOOD_CBPropertyChange(evt);
            }
        });

        jLabel4.setText("Adresse de livraison ; ");

        Adresse_TP.setColumns(20);
        Adresse_TP.setRows(5);
        Adresse_TP.setText("Rue de herve,25\n4030 Grivegnée\nBelgium");
        jScrollPane2.setViewportView(Adresse_TP);

        DELIVERY_GOODS_OK.setText("OK");
        DELIVERY_GOODS_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELIVERY_GOODS_OKActionPerformed(evt);
            }
        });

        jLabel9.setText("Nom Client : ");

        Nom_TF.setText("Claude Vilvens");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(DELIVERYGOOD_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(144, 144, 144)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Nom_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel14)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(DELIVERY_GOODS_OK)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(16, 16, 16)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DELIVERYGOOD_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Nom_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(DELIVERY_GOODS_OK)
                .addContainerGap())
        );

        TABS.addTab("DELIVERY_GOODS", jPanel5);

        Appareils_jTABLE1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NumSerie", "Prix de vente", "IdClient", ""
            }
        ));
        jScrollPane3.setViewportView(Appareils_jTABLE1);
        if (Appareils_jTABLE1.getColumnModel().getColumnCount() > 0) {
            Appareils_jTABLE1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Liste des ventes réalisées durant la session");

        LIST_SALES_OK.setText("OK");
        LIST_SALES_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIST_SALES_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel10)
                .addGap(0, 501, Short.MAX_VALUE))
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LIST_SALES_OK))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(LIST_SALES_OK))
        );

        TABS.addTab("LIST_SALES", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TABS)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TABS, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if (isConnect()) {
        closeConnection();
    }
}//GEN-LAST:event_formWindowClosing

    private void BT_verifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_verifierActionPerformed

    }//GEN-LAST:event_BT_verifierActionPerformed

    private void BUY_GOODS_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUY_GOODS_OKActionPerformed
        Vector BuyGoods = new Vector();
        BuyGoods.add(NumSerie_TF.getText());
        BuyGoods.add(modePaiement_CB.getSelectedItem());
        
        RequestDISMAP req = new RequestDISMAP(BUY_GOODS_REQUEST, BuyGoods);
        GSocket.Send(req);
        System.out.println("Apres la requete");
        //Attente de reponse du serveur
        ResponseDISMAP rep = (ResponseDISMAP) GSocket.Receive();
        System.out.println("Apres la réponse du serveur");

        if (rep.getCodeRetour() == YES) {
 
            JOptionPane.showMessageDialog(this, "Paiement OK! " + " !", "Client CheckIn", JOptionPane.INFORMATION_MESSAGE, null);
            LOGIN_OK.setEnabled(false);
            SEARCH_GOODS_OK.setEnabled(true);
            TAKE_GOODS_OK.setEnabled(false);
            BUY_GOODS_OK.setEnabled(false);
            DELIVERY_GOODS_OK.setEnabled(true);
            LIST_SALES_OK.setEnabled(true);
        } 
        else if (rep.getCodeRetour() == ALREADY_PAIED)
        {
            JOptionPane.showMessageDialog(this, "Vous avez déjà payé ! !", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
        }
        else if (rep.getCodeRetour() == BAD_PAIEMENT)
        {
            JOptionPane.showMessageDialog(this, "Mauvais moyen de paiement... Paiement refusé ! ", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_BUY_GOODS_OKActionPerformed

    private void NumSerie_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumSerie_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumSerie_TFActionPerformed

    private void TAKE_GOODS_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAKE_GOODS_OKActionPerformed
        Vector TakeGoods = new Vector();
        numeroSerieCourant= Integer.valueOf(NumSerie_TF.getText());
        TakeGoods.add(NumSerie_TF.getText());

        RequestDISMAP req = new RequestDISMAP(TAKE_GOODS_REQUEST, TakeGoods);
        GSocket.Send(req);
        System.out.println("Apres la requete");
        //Attente de reponse du serveur
        ResponseDISMAP rep = (ResponseDISMAP) GSocket.Receive();
        System.out.println("Apres la réponse du serveur");

        if (rep.getCodeRetour() == YES) {
            Vector vRetour = (Vector) rep.getChargeUtile();
            JOptionPane.showMessageDialog(this, "Reservation OK! "+"\n" +" numéro série:" + vRetour.get(0) +"\n" +"Prix définitif :" + vRetour.get(1) +" euros" + " !", "Client CheckIn", JOptionPane.INFORMATION_MESSAGE, null);
            SEARCH_GOODS_OK.setEnabled(true);
            TAKE_GOODS_OK.setEnabled(false);
            BUY_GOODS_OK.setEnabled(true);
            DELIVERY_GOODS_OK.setEnabled(false);
            LIST_SALES_OK.setEnabled(true);
            NumSerie_TF.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Appareil plus disponible !", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_TAKE_GOODS_OKActionPerformed

    private void LOGIN_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_OKActionPerformed
        try {
            //Récupération des informations
            
            
            System.out.println("pass=" +TF_password.getText());
            // register the BouncyCastleProvider with the Security Manager
            Security.addProvider(new BouncyCastleProvider());
            
            String plainString = TF_password.getText();
            
            MessageDigest messageDigest = MessageDigest.getInstance("SHA-512");
            byte[] hashedString = messageDigest.digest(plainString.getBytes());
            
            
            Vector vLogin = new Vector();
            vLogin.add(TF_user.getText());
            vLogin.add(hashedString);
            RequestDISMAP req = new RequestDISMAP(LOGIN_REQUEST, vLogin);
            GSocket.Send(req);
            System.out.println("Apres la requete");
            //Attente de reponse du serveur
            ResponseDISMAP rep = (ResponseDISMAP) GSocket.Receive();
            System.out.println("Apres la réponse du serveur");
            
            if (rep.getCodeRetour() == YES)
            {
                JOptionPane.showMessageDialog(this, "Login réalisée avec succès !", "Client CheckIn", JOptionPane.INFORMATION_MESSAGE, null);
                LOGIN_OK.setEnabled(false);
                SEARCH_GOODS_OK.setEnabled(true);
                TAKE_GOODS_OK.setEnabled(true);
                BUY_GOODS_OK.setEnabled(false);
                DELIVERY_GOODS_OK.setEnabled(false);
                LIST_SALES_OK.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Login échouée !", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LOGIN_OKActionPerformed

    private void TF_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_passwordActionPerformed

    private void Deconnect_BoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deconnect_BoutonActionPerformed

        closeConnection();
        Connect_Bouton.setEnabled(true);
        Deconnect_Bouton.setEnabled(false);
    }//GEN-LAST:event_Deconnect_BoutonActionPerformed

    private void Connect_BoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Connect_BoutonActionPerformed

        System.out.println("Tentative de connexion au serveur Reservation ...");
        GSocket.ConnectServeur(Serveur_TextField.getText(), Integer.parseInt(Port_TextField.getText()));
        if(GSocket.getCSocket() != null)
        {
            System.out.println("Connexion au serveur Reservation réalisé !");

            JOptionPane.showMessageDialog(this, "Connexion réalisée avec succès !", "Client Login", JOptionPane.INFORMATION_MESSAGE, null);

            Connect_Bouton.setEnabled(false);
            Deconnect_Bouton.setEnabled(true);
            LOGIN_OK.setEnabled(true);
            CREATE_USER_BUTTON.setEnabled(true);
            connect = true;
        }
        else
        {
             JOptionPane.showMessageDialog(this, "Connexion impossible !", "Client Login", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_Connect_BoutonActionPerformed

    private void SEARCH_GOODS_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_GOODS_OKActionPerformed

                DefaultTableModel dtm = (DefaultTableModel) this.Appareils_jTABLE.getModel();
                for (int i = dtm.getRowCount(); i > 0; --i) {
                        dtm.removeRow(i - 1);
                    }
                Vector VList = new Vector();
                VList.add(TypePrecis_CB.getSelectedItem().toString());
                
                RequestDISMAP req = new RequestDISMAP(SEARCH_GOODS_REQUEST, VList);
        
                GSocket.Send(req);
        
                //Attente de reponse du serveur
                ResponseDISMAP rep = (ResponseDISMAP) GSocket.Receive();
                List<Object> res = (List<Object>) rep.getChargeUtile();
        
                if (rep.getCodeRetour() == YES) {
                        for (int i = 0; i < res.size(); i++) {
                                System.out.println(res.get(i));
                                dtm.addRow((Vector) res.get(i));
                            }
            
                    } else {
                        JOptionPane.showMessageDialog(this, "Aucun Appareil de ce type présent dans le mummystore, désolé... !", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
                    }
    }//GEN-LAST:event_SEARCH_GOODS_OKActionPerformed

    private void CREATE_USER_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATE_USER_BUTTONActionPerformed
        CreerUser cu = new CreerUser(this, true);
        cu.setVisible(true);
        
        Vector vLogin = new Vector();
        vLogin.add(cu.getLOGIN_TF());
        vLogin.add(cu.getPWD_TF());

        RequestDISMAP req = new RequestDISMAP(USER_INSERT_REQUEST, vLogin);
        GSocket.Send(req);
        System.out.println("Apres la requete");
        //Attente de reponse du serveur
        ResponseDISMAP rep = (ResponseDISMAP) GSocket.Receive();
        System.out.println("Apres la réponse du serveur");

        if (rep.getCodeRetour() == YES) {
            JOptionPane.showMessageDialog(this, "User créé avec succès !", "Client CheckIn", JOptionPane.INFORMATION_MESSAGE, null);
        } else {
            JOptionPane.showMessageDialog(this, "Création User failed", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_CREATE_USER_BUTTONActionPerformed

    private void DELIVERYGOOD_CBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELIVERYGOOD_CBMousePressed
        
    }//GEN-LAST:event_DELIVERYGOOD_CBMousePressed

    private void DELIVERYGOOD_CBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DELIVERYGOOD_CBPropertyChange
        this.Adresse_TP.setEnabled(true);
    }//GEN-LAST:event_DELIVERYGOOD_CBPropertyChange

    private void DELIVERYGOOD_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELIVERYGOOD_CBActionPerformed
       if(DELIVERYGOOD_CB.getSelectedIndex()==0)
       {
        this.Adresse_TP.setEnabled(false);
        Adresse_TP.setText("Retiré dans le mummystore");
       }
       else 
       {
        this.Adresse_TP.setEnabled(true);
        Adresse_TP.setText("Rue de herve,25 "+ "\n" + "4030 Grivegnée" + "\n" + "BELGIQUE");
       }
    }//GEN-LAST:event_DELIVERYGOOD_CBActionPerformed

    private void DELIVERY_GOODS_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELIVERY_GOODS_OKActionPerformed
        Vector DeliveryGoods = new Vector();
        DeliveryGoods.add(DELIVERYGOOD_CB.getSelectedIndex()); // type
        DeliveryGoods.add(numeroSerieCourant); //numSerie pour faire la facture
        DeliveryGoods.add(Adresse_TP.getText());
        DeliveryGoods.add(this.Nom_TF.getText());
        DeliveryGoods.add(modePaiement_CB.getSelectedItem().toString());
        RequestDISMAP req = new RequestDISMAP(DELIVERY_GOODS_REQUEST, DeliveryGoods);
        GSocket.Send(req);
        System.out.println("Apres la requete");
        //Attente de reponse du serveur
        ResponseDISMAP rep = (ResponseDISMAP) GSocket.Receive();
        System.out.println("Apres la réponse du serveur");
        String Facture = null;
        if (rep.getCodeRetour() == YES) 
        {
            Vector vRetour = (Vector) rep.getChargeUtile();
            Facture = vRetour.get(0).toString();
            String s = new String(NumSerie_TF.getText().toString());
            
            VentesRealiseeSession.add(Integer.valueOf(s));
            System.out.println("Vector v=" + VentesRealiseeSession);
            TAKE_GOODS_OK.setEnabled(true);
            BUY_GOODS_OK.setEnabled(false);
            DELIVERY_GOODS_OK.setEnabled(false);
            NumSerie_TF.setEnabled(true);
            JOptionPane.showMessageDialog(this, "OUI !" + "\n" + "Voici votre facture : " +"\n" + Facture , "Client CheckIn", JOptionPane.INFORMATION_MESSAGE, null);
        } else {
            JOptionPane.showMessageDialog(this, "Problème technique !", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_DELIVERY_GOODS_OKActionPerformed

    private void LIST_SALES_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIST_SALES_OKActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.Appareils_jTABLE1.getModel();
                for (int i = dtm.getRowCount(); i > 0; --i) {
                        dtm.removeRow(i - 1);
                    }

                Vector v = new Vector();
                for(int i =0;i<VentesRealiseeSession.size();i++)
                        {
                            v.add(VentesRealiseeSession.get(i));
                        };
                RequestDISMAP req = new RequestDISMAP(LIST_SALES_REQUEST, v); // je passe tous les numsSerie pour récupérer totes les factures et afficher
        
                GSocket.Send(req);
        
                //Attente de reponse du serveur
                ResponseDISMAP rep = (ResponseDISMAP) GSocket.Receive();
                List<Object> res = (List<Object>) rep.getChargeUtile();
        
                if (rep.getCodeRetour() == YES) {
                        for (int i = 0; i < res.size(); i++) 
                        {
                                System.out.println(res.get(i));
                                dtm.addRow((Vector) res.get(i));
                            }
            
                    } else {
                        JOptionPane.showMessageDialog(this, "Aucun Appareil vendus, désolé... !", "Client CheckIn", JOptionPane.ERROR_MESSAGE, null);
                    }
    }//GEN-LAST:event_LIST_SALES_OKActionPerformed

    

   

    public void closeConnection() {
        //RequestTRAMAP req = new RequestTRAMAP(LOGOUT_REQUEST, null);
       // GSocket.Send(req);
        GSocket.Close();

        Connect_Bouton.setEnabled(true);
        Deconnect_Bouton.setEnabled(false);
        connect = false;
    }

    public void sendPortTimeOut(Object obj) {
        GSocket.Send(obj);
    }

    private boolean isConnect() {
        return connect;
    }

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Adresse_TP;
    private javax.swing.JTable Appareils_jTABLE;
    private javax.swing.JTable Appareils_jTABLE1;
    private javax.swing.JButton BUY_GOODS_OK;
    private javax.swing.JButton CREATE_USER_BUTTON;
    private javax.swing.JButton Connect_Bouton;
    private javax.swing.JComboBox DELIVERYGOOD_CB;
    private javax.swing.JButton DELIVERY_GOODS_OK;
    private javax.swing.JButton Deconnect_Bouton;
    private javax.swing.JLabel LB_machine;
    private javax.swing.JLabel LB_port;
    private javax.swing.JButton LIST_SALES_OK;
    private javax.swing.JButton LOGIN_OK;
    private javax.swing.JTextField Nom_TF;
    private javax.swing.JTextField NumSerie_TF;
    private javax.swing.JTextField Port_TextField;
    private javax.swing.JButton SEARCH_GOODS_OK;
    private javax.swing.JTextField Serveur_TextField;
    private javax.swing.JTabbedPane TABS;
    private javax.swing.JButton TAKE_GOODS_OK;
    private javax.swing.JTextField TF_password;
    private javax.swing.JTextField TF_user;
    private javax.swing.JPanel TabConnexion;
    private javax.swing.JComboBox TypePrecis_CB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JComboBox modePaiement_CB;
    // End of variables declaration//GEN-END:variables
}
